// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glsomtrgsqjphykedbph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsc29tdHJnc3FqcGh5a2VkYnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTAwNDIsImV4cCI6MjA2MzUyNjA0Mn0.GmYIWXmGg_fWDwPwOkxt1HGQ3p3vNdDGi6N1vDXqmL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);